In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from joblib import Parallel, delayed
from tqdm import tqdm
from itertools import product
from itertools import permutations
from itertools import combinations
from pyEDM import *
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Ridge
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.base import BaseEstimator, TransformerMixin
import time
import os
from copy import deepcopy
import math
import random
from sklearn.metrics import root_mean_squared_error
from scipy.stats import ttest_ind
import pickle
import ast
import json



from IPython.display import display, HTML
display(HTML('<style>.container { width:90% !important; }</style>'))

import warnings
warnings.filterwarnings("ignore", 
    message="A worker stopped while some jobs were given to the executor.",
    module="joblib.externals.loky.process_executor")

In [2]:
def get_block(data, num_lags=1, tau=1):
    ''' Get a dataframe with all the possible valid lags of the variables. '''
    
    block = pd.concat([data[var].shift(lag*tau).rename(f'{var}(t-{lag*tau})') for lag in range(num_lags+1) for var in data.columns], axis=1)

    return block
def get_xmap_results_smap(block, target, embeddings, Tp, theta, lib, pred):
    '''Function to do exhaustive search of embeddings.'''
    
    def compute_rho(block, target, embedding, Tp, theta, lib, pred):
        xmap = SMap(dataFrame=block, target=target, columns=embedding, Tp=Tp, theta=theta, embedded=True, lib=lib, pred=pred, noTime=True)
        rho = xmap['predictions'][['Observations', 'Predictions']].corr().iloc[0,1]
        return embedding, xmap['predictions'], rho

    xmap_results = pd.DataFrame(columns=['embedding', 'rho'])
    xmap_results = Parallel(n_jobs=-1)(delayed(compute_rho)(block, target, embedding, Tp, theta, lib, pred) for embedding in embeddings)
    xmap_results = pd.DataFrame(xmap_results, columns=['embedding', 'result', 'rho'])
    xmap_results = xmap_results.sort_values(by='rho', ascending=False).reset_index(drop=True)
    
    return xmap_results

def get_valid_lags_tau(block, target, tau, num_lags, system_variables):
    
    # Get lags of system variables
    system_variable_lags = []
    for var in system_variables:
        var_lags = [f'{var}(t{i})' if i < 0 else f'{var}(t-{i})' for i in range(num_lags * tau, 1)]
        var_lags = var_lags[::tau][:num_lags]
        system_variable_lags = system_variable_lags + var_lags
    
    # Remove (t-0) lag of target variable from valid_lags
    valid_lags = [x for x in system_variable_lags if x[-4:-1] != f'{target}(t-0)']

                    
    return valid_lags


def create_single_model(E,theta,target,i_cols,lib, pred,HAB_embed,showPlot=False):
    driver = f'{target}(t-0)'
    cols = i_cols + [driver]
    result = SMap(
        dataFrame = HAB_embed, 
        columns = cols,
        target = driver,
        lib = lib,  # Library from rows 0 to 700
        pred = pred,
        E = E+1,
        theta=theta,
        noTime=True,
        showPlot = showPlot,
        embedded=True,
        ignoreNan = True
    )
    return result

def thresh_bloom_binary_prediction(obs,pred,threshold=8.03199999999999):
    #obs_bloom_95 = np.percentile(obs, 95) #incorrect
    #pred_bloom_95 = np.percentile(pred, 95) #incorrect
    obs_blooms = obs > threshold
    pred_blooms = pred > threshold
    Accuracy = 1 - (obs_blooms ^ pred_blooms).mean()
    True_pos = (obs_blooms & pred_blooms).sum() / obs_blooms.sum()
    False_pos = ((~obs_blooms) & pred_blooms).sum() / (~obs_blooms).sum()
    True_neg = ((~obs_blooms) & (~pred_blooms)).sum() / (~obs_blooms).sum()
    False_neg = (obs_blooms & (~pred_blooms)).sum() / obs_blooms.sum()
    
    return [Accuracy, True_pos, False_pos, True_neg, False_neg]


def create_model(data,system_variables,target,Tp,num_lags,tau,theta_list,lib,pred):
    HAB_embed_block = get_block(data,50)
    valid_lags = get_valid_lags_tau(HAB_embed_block, target, tau, num_lags, system_variables)
    HAB_embeddings = {}
    for E in range(3,8):
        # Get random embeddings using valid lags
        embeddings = set()
        sample = 500
        max_trials = 500
        trials = 0
        while len(embeddings) < sample and trials < max_trials:
            embedding = tuple(random.sample(valid_lags, E))
            sorted_embedding = tuple(sorted(embedding))
            if sorted_embedding not in embeddings:
                embeddings.add(sorted_embedding)
            trials += 1
        embeddings = [list(embedding) for embedding in embeddings]
        HAB_embeddings['{0}'.format((target, E))] = embeddings
        E_list = range(3,8)


        
    total_iterations = len(E_list) * len(theta_list)

    parameters = pd.DataFrame(columns=['target', 'columns', 'E', 'theta', 'rho', 'rmse', 'pred'])

    with tqdm(total=total_iterations) as pbar:
        for E, theta in product(E_list, theta_list):

            key = [key for key in HAB_embeddings.keys() if eval(key)[0] == target and eval(key)[1] == E] #HAB_embeddings["('Avg_Chloro', 4, 0, 6)"][0]
            embeddings = HAB_embeddings[key[0]]
            for embedding in embeddings:
                smap_model = create_single_model(E,theta,target,embedding,lib, pred,HAB_embed_block,showPlot=False)
                df = smap_model['predictions']
                rho = df[['Observations', 'Predictions']].corr().iloc[0,1]
                rmse = root_mean_squared_error(df['Observations'].iloc[1:-1], df['Predictions'].iloc[1:-1])
                #bbp = thresh_bloom_binary_prediction(df['Observations'].iloc[1:-1],df['Predictions'].iloc[1:-1])

                new_row = {'target': target, 'columns': embedding + [f'{target}(t-0)'], 'E': E,'theta':theta, 'rho':rho, 'rmse':rmse, 'pred':df['Predictions']}
                parameters.loc[len(parameters)] = new_row

            

            pbar.update(1)
    parameters.sort_values(by='rho',ascending=False)
    return parameters

In [3]:
def ensemble_binary_bloom(parameters_df,n=300,p=0.05,samp=1,bloom_thresh=8.013):
    parameters_df = parameters_df.iloc[:n*samp].sample(n)
    sum = np.zeros(np.array(parameters_df['pred'].iloc[0][1:]).size)
    for i in range(n):
        curr = np.array(parameters_df['pred'].iloc[i][1:]) > bloom_thresh#np.percentile(parameters_df['pred'].iloc[i].iloc[1:],95)#
        sum = sum + curr
    return sum > (n*p)

'''
@parameters
data - dataframe of data containing column for target and desired system variables'
system variables - variables contained in system to be used for prediction
target - variable that will be forecasted (also used in prediction)
Tp - IDK
E - number of lags we go back
tau - step size that we go back at
theta_list - list of theta values to be used in ensemble model
lib - library used for prediction
pred - prediction length

@return
returns forecast for next time step given the dataframe 
'''

def next_forecast(data,system_variables,target,Tp,E,tau,theta_list,lib,pred,p=0.05):
    lib = '1 1012'
    pred = '1013 1602'
    parameters = create_model(data,system_variables,target,Tp,E,tau,theta_list,lib,pred)
    return parameters

# Testings

In [4]:

paper_data = pd.read_csv('Data/carter_data_w_gaps.csv') #DESIRED DATAPATH

paper_data = paper_data.set_index('time')
paper_data['Time'] = paper_data.index.astype(int)
paper_data['Avg_Chloro'] #= paper_data['Avg_Chloro'].apply(np.log1p) #LOG AMPUTATION
#IMPUTE HAB DATA
#Build basic linear regression model as sanity check
# Custom impute missing values with the average of the value in front and behind of it 
class ForwardBackwardImputer(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_filled_forward = X.fillna(method='ffill').fillna(method='bfill')
        X_filled_backward = X.fillna(method='bfill').fillna(method='ffill')

        return (X_filled_forward + X_filled_backward) / 2


Imputer = ForwardBackwardImputer()
paper_data = paper_data.apply(pd.to_numeric, errors='coerce')
Imputer.fit(paper_data)
paper_data = Imputer.transform(paper_data)#COMMENT OUT IF DONT WANT MEAN MPUTE
paper_data
HAB_embed = get_block(paper_data,50)
HAB_embed

KeyError: "None of ['time'] are in the columns"

In [9]:
data = paper_data
system_variables = [
 'Total_Diatoms',
 'Total_Dinoflagellates',
 'Total_Phytoplankton',
 'Ammonium',
 'Avg_Phaeo',
 'BOT_SAL_PSU',
 'BOT_TEMP_C',
 'BOT_DENS_kgm3',
 'BOT_DENS_'
 'Nitrate',
 'Phaeo1',
 'Phaeo2',
 'Total_Cochlodinium_spp',
 'Total_Prorocentrum_spp'] #SYSTEM VARIABLES

target = 'Avg_Chloro' #TARGET
system_variables = system_variables
Tp = 1
E = 3 # up to -2 
tau = -1
theta_list = [1,5,9,15,25,35,45]
lib = '1 1012'  # Library from rows 0 to 700
pred = '1013 1602'


preds = next_forecast(data,system_variables,target,Tp,E,tau,theta_list,lib,pred)
preds

100%|██████████| 35/35 [36:28<00:00, 62.54s/it]

,target,columns,E,theta,rho,rmse,pred
0,Avg_Chloro,"[BOT_TEMP_C(t-1), Total_Cochlodinium_spp(t-0),...",3,1,0.579143,50.982645,0 NaN 1 1.690609 2 2.23...
1,Avg_Chloro,"[Avg_Phaeo(t-1), Nitrate(t-1), Total_Diatoms(t...",3,1,0.697221,45.158525,0 NaN 1 1.555895 2 2.05...
2,Avg_Chloro,"[Avg_Phaeo(t-2), Phaeo1(t-0), Total_Diatoms(t-...",3,1,0.330480,59.774352,0 NaN 1 1.791763 2 2.08...
3,Avg_Chloro,"[Phaeo1(t-1), Total_Dinoflagellates(t-0), Tota...",3,1,0.562896,51.553694,0 NaN 1 1.589533 2 2.32...
4,Avg_Chloro,"[BOT_SAL_PSU(t-0), BOT_TEMP_C(t-1), Nitrate(t-...",3,1,0.571678,51.268654,0 NaN 1 1.476061 2 2.16...
...,...,...,...,...,...,...,...
17411,Avg_Chloro,"[Ammonium(t-2), BOT_SAL_PSU(t-1), Phaeo1(t-1),...",7,45,0.849389,369.456622,0 NaN 1 1.209464 2 1.38...
17412,Avg_Chloro,"[BOT_TEMP_C(t-0), Phaeo1(t-1), Total_Cochlodin...",7,45,0.116648,380.277781,0 NaN 1 1.600749 2 1.73...
17413,Avg_Chloro,"[BOT_SAL_PSU(t-0), BOT_SAL_PSU(t-1), Total_Din...",7,45,0.067204,508.739224,0 NaN 1 1.465497 2 1.13588...
17414,Avg_Chloro,"[Ammonium(t-2), Avg_Phaeo(t-1), BOT_TEMP_C(t-0...",7,45,-0.038783,204.909465,0 NaN 1 3.374548 2 1.26...
17415,Avg_Chloro,"[BOT_TEMP_C(t-2), Phaeo1(t-0), Phaeo2(t-0), To...",7,45,0.120437,178.868733,0 NaN 1 1.274309 2 0.27...

In [10]:
preds['pred'] = preds['pred'].apply(list)
preds.to_csv('100_sample_carter_models.csv') #TO SAVE (BE CAREFUL ABOUT OVERWRITING)

# DEYLE DATASET

In [7]:

paper_data = pd.read_csv('Data/orig_block.csv') #DESIRED DATAPATH
cols_to_drop = [col for col in paper_data.columns if '1wk' in col or '_2wk' in col]
paper_data = paper_data.drop(columns=cols_to_drop)

paper_data['Time'] = paper_data.index.astype(int)
# paper_data['Avg_Chloro'] = paper_data['chlA'].apply(np.log1p) #LOG AMPUTATION
#IMPUTE HAB DATA
#Build basic linear regression model as sanity check
# Custom impute missing values with the average of the value in front and behind of it 
class ForwardBackwardImputer(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_filled_forward = X.fillna(method='ffill').fillna(method='bfill')
        X_filled_backward = X.fillna(method='bfill').fillna(method='ffill')

        return (X_filled_forward + X_filled_backward) / 2


Imputer = ForwardBackwardImputer()
paper_data = paper_data.apply(pd.to_numeric, errors='coerce')
Imputer.fit(paper_data)
paper_data = Imputer.transform(paper_data)#COMMENT OUT IF DONT WANT MEAN MPUTE
paper_data['Time']
HAB_embed = get_block(paper_data,50)
HAB_embed

/var/folders/1_/l6tr0bbn3mb7vblmfq8qmf_40000gn/T/ipykernel_55121/911354117.py:18: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X_filled_forward = X.fillna(method='ffill').fillna(method='bfill')
/var/folders/1_/l6tr0bbn3mb7vblmfq8qmf_40000gn/T/ipykernel_55121/911354117.py:19: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X_filled_backward = X.fillna(method='bfill').fillna(method='ffill')

,serial_day(t-0),chlA(t-0),nitrate(t-0),phosphate(t-0),silicate(t-0),nitrite(t-0),nitrate_phosphate_ratio(t-0),N_star(t-0),Si_star(t-0),SST(t-0),...,phosphate(t-50),silicate(t-50),nitrite(t-50),nitrate_phosphate_ratio(t-50),N_star(t-50),Si_star(t-50),SST(t-50),WIND_SPD(t-50),U_WIND(t-50),Time(t-50)
0,725662.0,0.430,2.520,0.295,2.355,0.020,8.542373,-2.200,2.06,19.118428,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,725669.0,0.920,2.110,0.305,2.605,0.115,6.918033,-2.770,2.30,19.229762,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,725676.0,0.615,1.915,0.370,0.450,0.020,5.175676,-4.005,0.08,19.083670,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,725683.0,0.655,0.155,0.330,1.500,0.020,0.469697,-5.125,1.17,18.651255,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,725690.0,0.410,0.200,0.320,2.000,0.030,0.625000,-4.920,1.68,18.196674,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1836,734926.0,1.790,0.940,0.280,4.930,0.120,3.357143,-3.540,4.65,14.007738,...,0.41,0.04,0.04,1.951220,-5.76,-0.37,14.589881,3.262202,0.422999,1786.0
1837,734933.0,1.995,4.360,0.450,7.690,0.270,9.688889,-2.840,7.24,13.920575,...,0.28,0.01,0.01,0.678571,-4.29,-0.27,14.330357,4.166964,-0.254430,1787.0
1838,734940.0,8.210,1.490,0.310,4.710,0.110,4.806452,-3.470,4.40,13.516654,...,0.30,0.02,0.02,1.133333,-4.46,-0.28,13.673810,4.640476,-0.054776,1788.0
1839,734947.0,2.775,3.760,0.600,6.280,0.230,6.266667,-5.840,5.68,13.329387,...,0.13,0.01,0.01,2.000000,-1.82,-0.12,13.511918,4.807660,1.236447,1789.0
1840,734954.0,2.410,10.520,1.020,11.560,0.310,10.313725,-5.800,10.54,13.217534,...,0.46,0.09,0.09,4.543478,-5.27,-0.37,13.647541,4.308062,1.633663,1790.0

In [8]:
data = paper_data
system_variables = ['N_star',
 'SST',
 'Si_star',
 'U_WIND',
 'WIND_SPD',
 'chlA',
 'nitrate',
 'nitrate_phosphate_ratio',
 'nitrite',
 'phosphate',
 'serial_day',
 'silicate'] #SYSTEM VARIABLES

target = 'chlA' #TARGET
system_variables = system_variables
Tp = 1
E = 3 # up to -2 
tau = -1
theta_list = [1,5,9,15,25,35,45]
lib = '1 1012'  # Library from rows 0 to 700
pred = '1013 1602'


preds = next_forecast(data,system_variables,target,Tp,E,tau,theta_list,lib,pred)
preds

100%|██████████| 35/35 [1:01:51<00:00, 106.03s/it]

,target,columns,E,theta,rho,rmse,pred
0,chlA,"[Si_star(t-0), chlA(t-1), silicate(t-0), chlA(...",3,1,0.392045,2.910554,0 NaN 1 4.561909 2 3.96884...
1,chlA,"[Si_star(t-0), chlA(t-0), phosphate(t-2), chlA...",3,1,0.400430,2.626286,0 NaN 1 4.418396 2 2.78114...
2,chlA,"[SST(t-1), WIND_SPD(t-2), silicate(t-1), chlA(...",3,1,0.431593,2.677264,0 NaN 1 5.293790 2 2.05433...
3,chlA,"[Si_star(t-0), nitrite(t-0), silicate(t-2), ch...",3,1,0.390983,2.765205,0 NaN 1 4.505228 2 3.02343...
4,chlA,"[WIND_SPD(t-2), nitrate(t-2), phosphate(t-0), ...",3,1,0.381926,2.582860,0 NaN 1 5.960740 2 3.01825...
...,...,...,...,...,...,...,...
17369,chlA,"[SST(t-0), SST(t-2), U_WIND(t-0), chlA(t-1), n...",7,45,0.044368,14.205142,0 NaN 1 0.025546 2 -36.33...
17370,chlA,"[SST(t-2), Si_star(t-2), nitrate_phosphate_rat...",7,45,-0.025076,48.989653,0 NaN 1 11.230529 2 5.62...
17371,chlA,"[SST(t-2), Si_star(t-2), nitrate(t-1), nitrite...",7,45,-0.023829,39.882537,0 NaN 1 7.604550 2 4.20...
17372,chlA,"[N_star(t-2), SST(t-1), Si_star(t-2), U_WIND(t...",7,45,0.017586,44.476356,0 NaN 1 3.609995 2 5.07...
17373,chlA,"[U_WIND(t-0), U_WIND(t-2), nitrate_phosphate_r...",7,45,0.017394,29.734201,0 NaN 1 9.005238 2 5.58...

In [9]:
preds['pred'] = preds['pred'].apply(list)
preds.to_csv('100_sample_deyle_models_not_logged.csv') #TO SAVE (BE CAREFUL ABOUT OVERWRITING)